//
// Generated file, do not edit! Created by nedtool 5.7 from ComputerMessage.msg.
//

#ifndef __COMPUTERMESSAGE_M_H
#define __COMPUTERMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>ComputerMessage.msg:2</tt> by nedtool.
 * <pre>
 * message ComputerMsg
 * {
 *     int id;
 *     string header;
 * }
 * </pre>
 */
class ComputerMsg : public ::omnetpp::cMessage
{
  protected:
    int id;
    ::omnetpp::opp_string header;

  private:
    void copy(const ComputerMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ComputerMsg&);

  public:
    ComputerMsg(const char *name=nullptr, short kind=0);
    ComputerMsg(const ComputerMsg& other);
    virtual ~ComputerMsg();
    ComputerMsg& operator=(const ComputerMsg& other);
    virtual ComputerMsg *dup() const override {return new ComputerMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual const char * getHeader() const;
    virtual void setHeader(const char * header);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ComputerMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ComputerMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __COMPUTERMESSAGE_M_H

